version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        path: _test\.go
    paths:
      - cmd/cli/testdata
      - third_party$
      - builtin$
      - examples$
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/pkg/errors"
              desc: "use stdlib instead"
    funlen:
      lines: -1
      statements: 50

    goconst:
      min-len: 2
      min-occurrences: 2

    gocyclo:
      min-complexity: 15
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    lll:
      line-length: 140
    nolintlint:
      allow-unused: false
      require-explanation: false
      require-specific: false
    dupl:
      # tokens count to trigger issue, 150 by default
      threshold: 250

formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/protobom/sbom-convert
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/protobom/sbom-convert)

  exclusions:
    generated: lax
    paths:
      - cmd/cli/testdata
      - third_party$
      - builtin$
      - examples$
