linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use stdlib instead"
  funlen:
    lines: -1
    statements: 50

  gci:
    no-inline-comments: false
    no-prefix-comments: true
    sections:
      - standard
      - default
      - prefix(github.com/bom-squad/go-cli)

    section-separators:
      - newLine
  goimports:
    local-prefixes: github.com/bom-squad/go-cli
  goconst:
    min-len: 2
    min-occurrences: 2

  gocyclo:
    min-complexity: 15
  gomnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
    ignored-functions:
      - strings.SplitN
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 250

linters:
  disable-all: true
  enable:
    #- goimports
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gci
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gofumpt
    - revive
    - gocognit
    - asciicheck
    - errorlint
    - forbidigo
    - importas
    - prealloc
    - tparallel
  # don't enable:
  # - scopelint
  # - gochecknoglobals
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - goimports
  # - testpackage
  # - golint (replaced by revive)
  # - wsl
  # - structcheck
  # - varcheck
  # - deadcode

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

run:
  timeout: 5m
  skip-dirs:
    - cmd/cli/testdata
