project_name: sbom-convert
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh {{ .ProjectName }}
    - ./scripts/manpages.sh {{ .ProjectName }}
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    ldflags:
      - -s -w -X {{ .ModulePath }}/cmd/cli.version={{.Version}}
    main: .
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# TODO: improve section: ref: https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

release:
 disable: false
 name_template: 'v{{ .Version }}'
 github:
   owner: '{{ .Env.ORG_NAME }}'
   name: '{{ .ProjectName }}'

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://github.com/{{ .Env.ORG_NAME }}/{{ .ProjectName }}
    description: |-
      A tool to convert between different Software Bill of Materials (SBOM) formats.
    maintainer: Ori Avraham <ori@manifestcyber.com>
    vendor: '{{ .Env.ORG_NAME }}'
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/{{ .ProjectName }}.bash
        dst: /usr/share/bash-completion/completions/{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.fish
        dst: /usr/share/fish/vendor_completions.d/{{ .ProjectName }}.fish
        file_info:
          mode: 0644
      - src: ./completions/{{ .ProjectName }}.zsh
        dst:  /usr/share/zsh/vendor-completions/_{{ .ProjectName }}
        file_info:
          mode: 0644
      - src: ./manpages/{{ .ProjectName }}.1.gz
        dst: /usr/share/man/man1/{{ .ProjectName }}.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/copyright
        file_info:
          mode: 0644
    formats:
    - apk
    - deb
    - rpm
    - archlinux
    dependencies:
    - git
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os | tolower }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

publishers:
  - name: fury.io
    ids:
    - packages
    env:
    - 'FURY_TOKEN={{ .Env.FURY_TOKEN }}'
    - 'FURY_ORG={{ .Env.ORG_NAME }}'
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

scoops:
  -
    repository:
      owner: '{{ .Env.ORG_NAME }}'
      name: scoop-bucket
    homepage: https://github.com/{{ .Env.ORG_NAME }}/{{ .ProjectName }}
    description: A tool to convert between different Software Bill of Materials (SBOM) formats.
    license: Apache-2.0

brews:
  - repository:
      owner: '{{ .Env.ORG_NAME }}'
      name: homebrew-tap
    homepage: https://github.com/{{ .Env.ORG_NAME }}/{{ .ProjectName }}
    goarm: "7"
    description: A tool to convert between different Software Bill of Materials (SBOM) formats.
    license: Apache-2.0
    folder: Formula
    install: |-
      bin.install "{{ .ProjectName }}"
      bash_completion.install "completions/{{ .ProjectName }}.bash" => "{{ .ProjectName }}"
      zsh_completion.install "completions/{{ .ProjectName }}.zsh" => "_{{ .ProjectName }}"
      fish_completion.install "completions/{{ .ProjectName }}.fish"
      man1.install "manpages/{{ .ProjectName }}.1.gz"

dockers:
- image_templates:
  - 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:{{ .Tag }}-amd64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/{{ .Env.ORG_NAME }}/{{ .ProjectName }}/main/README.md"
  - "--label=io.artifacthub.package.logo-url=https://todo.add/file.png"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Ori Avraham\",\"email\":\"ori@manifestcyber.com\"}]"
  - "--label=io.artifacthub.package.license=Apache-2.0"
  - "--label=org.opencontainers.image.description=A tool to convert between different Software Bill of Materials (SBOM) formats."
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.ORG_NAME }}/{{ .ProjectName }}"
  - "--platform=linux/amd64"
  extra_files:
  - scripts/entrypoint.sh
- image_templates:
  - 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:{{ .Tag }}-arm64'
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/{{ .Env.ORG_NAME }}/{{ .ProjectName }}/main/README.md"
  - "--label=io.artifacthub.package.logo-url=https://todo.add/file.png"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Ori Avraham\",\"email\":\"ori@manifestcyber.com\"}]"
  - "--label=io.artifacthub.package.license=Apache-2.0"
  - "--label=org.opencontainers.image.description=A tool to convert between different Software Bill of Materials (SBOM) formats."
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/{{ .Env.ORG_NAME }}/{{ .ProjectName }}"
  - "--platform=linux/arm64"
  goarch: arm64
  extra_files:
  - scripts/entrypoint.sh
docker_manifests:
- name_template: 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:{{ .Tag }}'
  image_templates:
  - 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:{{ .Tag }}-amd64'
  - 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:{{ .Tag }}-arm64'
- name_template: 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:latest'
  image_templates:
  - 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:{{ .Tag }}-amd64'
  - 'ghcr.io/{{ .Env.ORG_NAME }}/{{ .ProjectName }}:{{ .Tag }}-arm64'
