package github

var CommandMetaData = map[string]actionMeta{
	"protobom_protobom": {
		Name:    "Protobom translation action",
		Author:  "Mikey Strauss (autogenerated)",
		Outputs: []actionOutput{},
	},
}

type actionMeta struct {
	Name    string
	Author  string
	Outputs []actionOutput
}

type actionOutput struct {
	Name        string
	Description string
}
