name: golangci-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  resolve-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    outputs:
      stable: ${{ steps.versions.outputs.GO_MINOR_VERSION_STABLE }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Determine Go versions
        id: versions
        uses: carabiner-dev/actions/go/versions@36a39ef667efe7112df8b1a534a4e37f35fad6fd # v1.2.6

  golangci:
    needs: resolve-versions
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ needs.resolve-versions.outputs.stable }}
          check-latest: true
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          args: --timeout=5m
          version: v2.12
